spring:
  application:
    name: SpringBoot_MicroService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Sureshjuvva@876
    url: jdbc:mysql://localhost:3306/user_management
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    info:
      enabled: true
    health:
      circuitbreakers:
        enabled : true
    endpoint:
      health:
        show-details: always

resilence4j:
  circuitbreaker:
    instances:
      TOKEN-VALIDATION-SERVICE:
        register-health-indicaor: true
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state : 3
        wait-duration-in-open-state: 5s

info:
  application:
    name: SpringBoot_MicroService
    description: springboot microservice demo
    version: 1.0.0

  cloud:
    function:
      definition: customProducer;customProcessor;customConsumer
    stream:
      bindings:
        customProducer-out-0:
          destination: first-topic
        customProcessor-in-0:
          destination: first-topic
        customProcessor-out-0:
          destination: second-topic
        customConsumer-in-0:
          destination: second-topic

kafka:
  binder:
    brokers:
      - localhost:9092
      - localhost:9093

